name: Scrape Data

on:
  schedule:
    - cron: '*/5 * * * *'  # This means the cron job will run every 5 minutes
  workflow_dispatch:  # This allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0' 

      - name: Install dependencies
        run: npm install

      - name: Run the scraper
        run: node scraper.js  # Run the scraper script

      - name: Commit and push updated data
        run: |
          git config --global user.email "nikithamorningstar@gmail.com"
          git config --global user.name "Wdevtri"
          git add .
          git commit -m "Update scraped data"
          git push
